Use Salt's service module to start the service
plus3it/nessus-agent-formula pull request #9
Opened 2020-10-27 22:56 UTC by jkunjoonju18

Every OS has different daemon service and evolves over time.
It's better to let Salt's "service" module handle the under pinnings
* https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.service.html

2020-10-28 20:47 UTC, lorengordon requested changes
@jkunjoonju18 This looks pretty reasonable, but can you please fix line 49, now that it is the `service` state instead of the `cmd` state?

```yaml
      - service: Start Nessus Agent
```

2020-10-29 13:43 UTC, lorengordon commented
@jkunjoonju18 fyi, i went ahead and updated your branch with the necessary fix.

2020-10-29 13:57 UTC, eemperor approved these changes

2020-10-29 14:24 UTC, lorengordon submitted a review, later dismissed

2020-10-29 21:04 UTC, lorengordon commented
@long Had to force the service name to lowercase to get this to work. Please take another look when you can!

2020-10-29 21:16 UTC, eemperor approved these changes
👍

2020-10-29 21:18 UTC, merged